language: objective-c

osx_image: xcode7.2

before_install:
- brew update
- brew install carthage

before_script:
- carthage bootstrap

script:
- xctool -project SwiftStateMachine.xcodeproj -scheme SwiftStateMachine build test
